---
abstract: 'interact with and control iTunes'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mac-iTunes
no_index:
  directory:
    - t
    - inc
requires:
  MP3::Info: '0'
  Mac::Path::Util: '0.07'
  Mac::PropertyList: '0'
  Test::Manifest: '1.14'
  Test::More: '0'
version: '1.23'
