# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mac-iTunes
version:      0.85
version_from: lib/iTunes.pm
installdirs:  site
requires:
    Mac::AppleScript:              0.03
    Mac::Path::Util:               0.07
    Mac::PropertyList:             0
    MP3::Info:                     0
    Test::Manifest:                0.9
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
