--- #YAML:1.0
name:                Mac-iTunes
version:             0.90
abstract:            interact with and control iTunes
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Mac::AppleScript:              0.03
    Mac::Path::Util:               0.07
    Mac::PropertyList:             0
    MP3::Info:                     0
    Test::Manifest:                1.14
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
